apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-eo3l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-eo3l
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-eo3l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-eo3l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-eo3l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kebc-tenant/rhtap-demo-app/hacbs-test-project-eo3l@sha256:1ff5bc4a46c29c70baf83ba55d4783331875cb7a45031cbc6797fbefa70906b7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
