apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-eo3l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kebc-tenant/rhtap-demo-app/hacbs-test-project-eo3l@sha256:1ff5bc4a46c29c70baf83ba55d4783331875cb7a45031cbc6797fbefa70906b7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
